# This is a basic workflow to help you get started with Actions

name: backend-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # variables
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        mongo-version: [4.2, 4.4]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Setup Nodejs version
      - name: Setup Node ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      
      # Setup MongoDB version
      - name: Setup Mongo ${{matrix.mongo-version}}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongo-version: ${{matrix.mongo-version}}
          
      # Run
      - name: Install Dependencies
        run: cd ./BackEnd && npm install
      
      # Test
      - name: Run test
        run: cd ./BackEnd && npm test
